### ISSUE TITLE
Problem importing AudioImpulseRunner

### ISSUE THREAD

**Issue by HasibAlAhmed** [edgeimpulse/linux-sdk-python#11]
I trained a model to detect keywords.
Now I am trying to deplyo the eim fie in my Raspberry py.
At first I went for the example code. 
In the script of classify.py in Eamples folder, this error occurs when it tries to execute 

`"from edge_impulse_linux.audio import AudioImpulseRunner"  `

the Error I got is:

```
Traceback (most recent call last):
  File "/home/pi/linux-sdk-python/examples/audio/classify.py", line 5, in <module>
    from edge_impulse_linux.audio import AudioImpulseRunner
  File "/home/pi/.local/lib/python3.9/site-packages/edge_impulse_linux/__init__.py", line 3, in <module>
    from edge_impulse_linux import image
  File "/home/pi/.local/lib/python3.9/site-packages/edge_impulse_linux/image.py", line 4, in <module>
    import cv2
  File "/home/pi/.local/lib/python3.9/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libopenjp2.so.7: cannot open shared object file: No such file or directory
```

What should be the solution?

**Comment by mmajchrzycki** [comment]
Hi @HasibAlAhmed 
You need to install these additional libraries:
```
sudo apt install libopenjp2-7 libgtk-3-0 libswscale-dev libavformat58 libavcodec58
```
I've upgraded the README to cover the issue. Thank you for reporting!
