### ISSUE TITLE
Error building: no module named 'skbuild'

### ISSUE THREAD

**Issue by ShawnHymel** [edgeimpulse/linux-sdk-python#14]
Trying to build on Ubuntu 18.04 on VirtualBox:

```
sgmustadio@sgmustadio-VirtualBox:~$ pip3 install edge_impulse_linux
Collecting edge_impulse_linux
  Downloading https://files.pythonhosted.org/packages/49/12/80abf52d92bba8caabdbff4d37ac00349d0890baa3cc845bad11fe85650b/edge_impulse_linux-1.0.6.tar.gz
Collecting PyAudio==0.2.11 (from edge_impulse_linux)
  Cache entry deserialization failed, entry ignored
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/ab/42/b4f04721c5c5bfc196ce156b3c768998ef8c0ae3654ed29ea5020c749a6b/PyAudio-0.2.11.tar.gz
Collecting numpy>=1.19 (from edge_impulse_linux)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/45/b7/de7b8e67f2232c26af57c205aaad29fe17754f793404f59c8a730c7a191a/numpy-1.21.6.zip (10.3MB)
    100% |████████████████████████████████| 10.3MB 209kB/s 
Collecting opencv-python==4.5.1.48 (from edge_impulse_linux)
  Downloading https://files.pythonhosted.org/packages/bb/08/9dbc183a3ac6baa95fabf749ddb531bd26256edfff5b6c2195eca26258e9/opencv-python-4.5.1.48.tar.gz (88.3MB)
    100% |████████████████████████████████| 88.3MB 24kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xt0tsuyp/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xt0tsuyp/opencv-python/
```

**Comment by ShawnHymel** [comment]
This is solved with a simple:

```
pip3 install --upgrade pip
```

So, we can close this issue. However, should I add the "upgrade pip" step to the docs to ensure users have the up-to-date version of pip?

**Comment by mmajchrzycki** [comment]
There is info about installing the most recent `Python` in the README. I've also added the info about installing `pip`.
