### ISSUE TITLE
object-detection example 

### ISSUE THREAD

**Issue by quantum-fusion** [edgeimpulse/linux-sdk-python#2]
I tried your example to create a REST server for object detection, shown here (https://docs.edgeimpulse.com/docs/object-detection).  

--
import http.server
from http.server import HTTPServer, BaseHTTPRequestHandler
import socketserver

PORT = 8082

Handler = http.server.SimpleHTTPRequestHandler

Handler.extensions_map={
    '.manifest': 'text/cache-manifest',
    '.html': 'text/html',
    '.png': 'image/png',
    '.jpg': 'image/jpg',
    '.svg': 'image/svg+xml',
    '.css': 'text/css',
    '.js': 'application/x-javascript',
    '.wasm': 'application/wasm',
    '': 'application/octet-stream', # Default
    }

httpd = socketserver.TCPServer(("", PORT), Handler)

print("serving at port", PORT)
httpd.serve_forever()
---

I tried to post to this server after downloading the neural net model that was created.
curl --request POST --url http://localhost:8082/ --data '{"inputs":{"Image":"'$(base64 ./car.jpg)'"}}'

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
        <title>Error response</title>
    </head>
    <body>
        <h1>Error response</h1>
        <p>Error code: 501</p>
        <p>Message: Unsupported method ('POST').</p>
        <p>Error code explanation: HTTPStatus.NOT_IMPLEMENTED - Server does not support this operation.</p>
    </body>
</html>

<img width="406" alt="Screen Shot 2021-04-14 at 11 25 12 AM" src="https://user-images.githubusercontent.com/10088099/115153269-0a3db000-a043-11eb-952c-fbe3ff6a9983.png">
<img width="1392" alt="Screen Shot 2021-04-14 at 11 25 25 AM" src="https://user-images.githubusercontent.com/10088099/115153272-0ca00a00-a043-11eb-9acc-a30f864e4dd7.png">
<img width="1406" alt="Screen Shot 2021-04-14 at 11 25 37 AM" src="https://user-images.githubusercontent.com/10088099/115153274-0f026400-a043-11eb-90d8-12af3026ca0f.png">

**Comment by quantum-fusion** [comment]
The car should only be detected 25% of the time and the truck should be detected 75% of the time, according to the web dashboard, however when I tried to do a curl post the command failed.  I also don't understand the interface to this system, because you have to look at embedded javascript in the browser.  I don't think this is REST API, and doesn't seem usable for REST api standards.  Please explain how this should be used, because the results don't seem favorable.

**Comment by quantum-fusion** [comment]
I tried to post to this server after downloading the neural net model that was created.
curl --request POST --url http://localhost:8082/ --data '{"inputs":{"Image":"'$(base64 ./car.jpg)'"}}'

<title>Error response</title>
Error response

Error code: 501

Message: Unsupported method ('POST').

**Comment by janjongboom** [comment]
@quantum-fusion This is a Python library to run your models from Python, you can use this library in a Python application to f.e. build a webserver - but there's no code in your server example regarding either this library, nor listening on any URL. It looks like you're mixing and matching various examples that are not related (this repo + the WebAssembly example it seems). 

My suggestion here:

1. Make sure you can run the image classification example from https://docs.edgeimpulse.com/docs/linux-python-sdk
2. If you have that, add a webserver to the script, e.g. like https://gist.github.com/nitaku/10d0662536f37a087e1b where you have a POST handler that reads the image, then passes it to the `runner.classifier` function.

**Comment by quantum-fusion** [comment]
@janjongboom I tried to install the python library, and it won't install. (https://github.com/edgeimpulse/linux-sdk-python/issues/3)

**Comment by quantum-fusion** [comment]
@janjongboom  I got the linux-sdk-python library installed for edge-impulse-linux like here (https://github.com/edgeimpulse/linux-sdk-python/issues/3).  Install was messy on MACOS. 

However, the install using the cli was great.  (https://docs.edgeimpulse.com/docs/edge-impulse-linux-macos).

I created a conda virtualENV like in the numpy example:

# Best practice, use an environment rather than install in the base env
conda create -n my-env

conda activate my-env

# If you want to install from conda-forge
conda config —env —add channels conda-forge

cd ./linux-sdk-python/examples/image

%python classify.py 

The python classify.py script has errors: 
--
Traceback (most recent call last):
  File "/Users/hottelet/linux-sdk-python/examples/image/classify.py", line 8, in <module>
    from edge_impulse_linux.image import ImageImpulseRunner
  File "/Users/hottelet/opt/anaconda3/envs/my-env/lib/python3.9/site-packages/edge_impulse_linux/__init__.py", line 2, in <module>
    from edge_impulse_linux import audio
  File "/Users/hottelet/opt/anaconda3/envs/my-env/lib/python3.9/site-packages/edge_impulse_linux/audio.py", line 5, in <module>
    from six.moves import queue
ModuleNotFoundError: No module named 'six'

**Comment by mmajchrzycki** [comment]
Hi @quantum-fusion 
You are missing Python `six` module. Try to install it with `pip`:
```
pip install six
```
Also, check if you've installed all dependencies form [requirements.txt](https://github.com/edgeimpulse/linux-sdk-python/blob/master/requirements.txt)

**Comment by mmajchrzycki** [comment]
Closing due to no activity.
