### ISSUE TITLE
Install failed on Raspberry Pi with "failed with error code 1 in None"

### ISSUE THREAD

**Issue by rdlauer** [edgeimpulse/linux-sdk-python#7]
Hi there - running into an issue with the install on a RPi 4. It looks to be a build issue with numpy possibly?

After [following the instructions](https://docs.edgeimpulse.com/docs/raspberry-pi-4) to set up the Edge Impulse CLI on an RPi, I then went to install the Python SDK with:

```
$ sudo apt-get install libatlas-base-dev libportaudio0 libportaudio2 libportaudiocpp0 portaudio19-dev
$ pip3 install edge_impulse_linux -i https://pypi.python.org/simple
```

Unfortunately it resolved in the following. Any ideas?

```
    ----------------------------------------
    Failed building wheel for numpy
    Running setup.py clean for numpy
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z11t01uf/numpy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
    Running from numpy source directory.
 
    `setup.py clean` is not supported, use one of the following instead:
 
      - `git clean -xdf` (cleans all files)
      - `git clean -Xdf` (cleans all versioned files, doesn't touch
                          files that aren't checked into the git repo)
 
    Add `--force` to your command to use it anyway if you must (unsupported).
 
 
    ----------------------------------------
    Failed cleaning build dir for numpy
  Failed to build cmake numpy
  Installing collected packages: setuptools, wheel, distro, pyparsing, packaging, scikit-build, cmake, pip, numpy
    Running setup.py install for cmake: started
      Running setup.py install for cmake: finished with status 'error'
      Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z11t01uf/cmake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qehuqa3n/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-qrs405gd --compile:
      Traceback (most recent call last):
        File "/tmp/pip-build-env-dzksoz7a/lib/python3.7/site-packages/skbuild/setuptools_wrap.py", line 560, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-dzksoz7a/lib/python3.7/site-packages/skbuild/cmaker.py", line 95, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-dzksoz7a/lib/python3.7/site-packages/skbuild/cmaker.py", line 82, in get_cmake_version
          "Problem with the CMake installation, aborting build. CMake executable is %s" % cmake_executable)
 
      Problem with the CMake installation, aborting build. CMake executable is cmake
 
      ----------------------------------------
  Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-z11t01uf/cmake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-qehuqa3n/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-qrs405gd --compile" failed with error code 1 in /tmp/pip-install-z11t01uf/cmake/
 
  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-qrs405gd --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.python.org/simple --extra-index-url https://www.piwheels.org/simple -- setuptools wheel scikit-build cmake pip "numpy==1.13.3; python_version=='3.6' and platform_machine != 'aarch64'" "numpy==1.19.3; python_version>='3.6' and sys_platform == 'linux' and platform_machine == 'aarch64'" "numpy==1.14.5; python_version=='3.7' and platform_machine != 'aarch64'" "numpy==1.17.3; python_version=='3.8' and platform_machine != 'aarch64'" "numpy==1.19.3; python_version>='3.9' and platform_machine != 'aarch64'"" failed with error code 1 in None
```

**Comment by rdlauer** [comment]
Following up on this issue. A day later I took another stab at the installation process...and it worked? Literally the only difference is that I rebooted the Pi overnight. 🤷
